// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: assets.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Assets_InitAssets_FullMethodName   = "/pb.Assets/InitAssets"
	Assets_FetchAssets_FullMethodName  = "/pb.Assets/FetchAssets"
	Assets_ChangeAssets_FullMethodName = "/pb.Assets/ChangeAssets"
)

// AssetsClient is the client API for Assets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsClient interface {
	// 初始化资产
	InitAssets(ctx context.Context, in *InitAssetsArgs, opts ...grpc.CallOption) (*InitAssetsReply, error)
	// 拉取玩家资产
	FetchAssets(ctx context.Context, in *FetchAssetsArgs, opts ...grpc.CallOption) (*FetchAssetsReply, error)
	// 变动玩家资产（资产不足则变动失败）
	ChangeAssets(ctx context.Context, in *ChangeAssetsArgs, opts ...grpc.CallOption) (*ChangeAssetsReply, error)
}

type assetsClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsClient(cc grpc.ClientConnInterface) AssetsClient {
	return &assetsClient{cc}
}

func (c *assetsClient) InitAssets(ctx context.Context, in *InitAssetsArgs, opts ...grpc.CallOption) (*InitAssetsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitAssetsReply)
	err := c.cc.Invoke(ctx, Assets_InitAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClient) FetchAssets(ctx context.Context, in *FetchAssetsArgs, opts ...grpc.CallOption) (*FetchAssetsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchAssetsReply)
	err := c.cc.Invoke(ctx, Assets_FetchAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsClient) ChangeAssets(ctx context.Context, in *ChangeAssetsArgs, opts ...grpc.CallOption) (*ChangeAssetsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeAssetsReply)
	err := c.cc.Invoke(ctx, Assets_ChangeAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsServer is the server API for Assets service.
// All implementations must embed UnimplementedAssetsServer
// for forward compatibility.
type AssetsServer interface {
	// 初始化资产
	InitAssets(context.Context, *InitAssetsArgs) (*InitAssetsReply, error)
	// 拉取玩家资产
	FetchAssets(context.Context, *FetchAssetsArgs) (*FetchAssetsReply, error)
	// 变动玩家资产（资产不足则变动失败）
	ChangeAssets(context.Context, *ChangeAssetsArgs) (*ChangeAssetsReply, error)
	mustEmbedUnimplementedAssetsServer()
}

// UnimplementedAssetsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetsServer struct{}

func (UnimplementedAssetsServer) InitAssets(context.Context, *InitAssetsArgs) (*InitAssetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAssets not implemented")
}
func (UnimplementedAssetsServer) FetchAssets(context.Context, *FetchAssetsArgs) (*FetchAssetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAssets not implemented")
}
func (UnimplementedAssetsServer) ChangeAssets(context.Context, *ChangeAssetsArgs) (*ChangeAssetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAssets not implemented")
}
func (UnimplementedAssetsServer) mustEmbedUnimplementedAssetsServer() {}
func (UnimplementedAssetsServer) testEmbeddedByValue()                {}

// UnsafeAssetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsServer will
// result in compilation errors.
type UnsafeAssetsServer interface {
	mustEmbedUnimplementedAssetsServer()
}

func RegisterAssetsServer(s grpc.ServiceRegistrar, srv AssetsServer) {
	// If the following call pancis, it indicates UnimplementedAssetsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Assets_ServiceDesc, srv)
}

func _Assets_InitAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitAssetsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServer).InitAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assets_InitAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServer).InitAssets(ctx, req.(*InitAssetsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Assets_FetchAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAssetsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServer).FetchAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assets_FetchAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServer).FetchAssets(ctx, req.(*FetchAssetsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Assets_ChangeAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAssetsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServer).ChangeAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Assets_ChangeAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServer).ChangeAssets(ctx, req.(*ChangeAssetsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// Assets_ServiceDesc is the grpc.ServiceDesc for Assets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Assets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Assets",
	HandlerType: (*AssetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAssets",
			Handler:    _Assets_InitAssets_Handler,
		},
		{
			MethodName: "FetchAssets",
			Handler:    _Assets_FetchAssets_Handler,
		},
		{
			MethodName: "ChangeAssets",
			Handler:    _Assets_ChangeAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assets.proto",
}
