// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.11.4
// source: assets.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitAssetsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           int64                  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`   // 用户ID
	Gold          int64                  `protobuf:"varint,2,opt,name=Gold,proto3" json:"Gold,omitempty"` // 资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAssetsArgs) Reset() {
	*x = InitAssetsArgs{}
	mi := &file_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAssetsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAssetsArgs) ProtoMessage() {}

func (x *InitAssetsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAssetsArgs.ProtoReflect.Descriptor instead.
func (*InitAssetsArgs) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{0}
}

func (x *InitAssetsArgs) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *InitAssetsArgs) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type InitAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"` // 资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAssetsReply) Reset() {
	*x = InitAssetsReply{}
	mi := &file_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAssetsReply) ProtoMessage() {}

func (x *InitAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAssetsReply.ProtoReflect.Descriptor instead.
func (*InitAssetsReply) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{1}
}

func (x *InitAssetsReply) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type ChangeAssetsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           int64                  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`       // 用户ID
	Gold          int64                  `protobuf:"varint,2,opt,name=Gold,proto3" json:"Gold,omitempty"`     // 金币
	Reason        int32                  `protobuf:"varint,3,opt,name=Reason,proto3" json:"Reason,omitempty"` // 变动原因
	Remark        string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`  // 变动备注
	Force         bool                   `protobuf:"varint,5,opt,name=Force,proto3" json:"Force,omitempty"`   // 是否强制执行变动操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAssetsArgs) Reset() {
	*x = ChangeAssetsArgs{}
	mi := &file_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAssetsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAssetsArgs) ProtoMessage() {}

func (x *ChangeAssetsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAssetsArgs.ProtoReflect.Descriptor instead.
func (*ChangeAssetsArgs) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeAssetsArgs) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *ChangeAssetsArgs) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *ChangeAssetsArgs) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *ChangeAssetsArgs) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ChangeAssetsArgs) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ChangeAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeAssets  *ChangeAssets          `protobuf:"bytes,1,opt,name=ChangeAssets,proto3" json:"ChangeAssets,omitempty"` // 实际变动的资产
	FinalAssets   *FinalAssets           `protobuf:"bytes,2,opt,name=FinalAssets,proto3" json:"FinalAssets,omitempty"`   // 变动后的最终资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAssetsReply) Reset() {
	*x = ChangeAssetsReply{}
	mi := &file_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAssetsReply) ProtoMessage() {}

func (x *ChangeAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAssetsReply.ProtoReflect.Descriptor instead.
func (*ChangeAssetsReply) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeAssetsReply) GetChangeAssets() *ChangeAssets {
	if x != nil {
		return x.ChangeAssets
	}
	return nil
}

func (x *ChangeAssetsReply) GetFinalAssets() *FinalAssets {
	if x != nil {
		return x.FinalAssets
	}
	return nil
}

type ChangeAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"` // 资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAssets) Reset() {
	*x = ChangeAssets{}
	mi := &file_assets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAssets) ProtoMessage() {}

func (x *ChangeAssets) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAssets.ProtoReflect.Descriptor instead.
func (*ChangeAssets) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeAssets) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type FinalAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"` // 资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalAssets) Reset() {
	*x = FinalAssets{}
	mi := &file_assets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalAssets) ProtoMessage() {}

func (x *FinalAssets) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalAssets.ProtoReflect.Descriptor instead.
func (*FinalAssets) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{5}
}

func (x *FinalAssets) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type FetchAssetsArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           int64                  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAssetsArgs) Reset() {
	*x = FetchAssetsArgs{}
	mi := &file_assets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAssetsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAssetsArgs) ProtoMessage() {}

func (x *FetchAssetsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAssetsArgs.ProtoReflect.Descriptor instead.
func (*FetchAssetsArgs) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{6}
}

func (x *FetchAssetsArgs) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type FetchAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=Gold,proto3" json:"Gold,omitempty"` // 资产
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAssetsReply) Reset() {
	*x = FetchAssetsReply{}
	mi := &file_assets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAssetsReply) ProtoMessage() {}

func (x *FetchAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAssetsReply.ProtoReflect.Descriptor instead.
func (*FetchAssetsReply) Descriptor() ([]byte, []int) {
	return file_assets_proto_rawDescGZIP(), []int{7}
}

func (x *FetchAssetsReply) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

var File_assets_proto protoreflect.FileDescriptor

const file_assets_proto_rawDesc = "" +
	"\n" +
	"\fassets.proto\x12\x02pb\"6\n" +
	"\x0eInitAssetsArgs\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x03R\x03UID\x12\x12\n" +
	"\x04Gold\x18\x02 \x01(\x03R\x04Gold\"%\n" +
	"\x0fInitAssetsReply\x12\x12\n" +
	"\x04Gold\x18\x01 \x01(\x03R\x04Gold\"~\n" +
	"\x10ChangeAssetsArgs\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x03R\x03UID\x12\x12\n" +
	"\x04Gold\x18\x02 \x01(\x03R\x04Gold\x12\x16\n" +
	"\x06Reason\x18\x03 \x01(\x05R\x06Reason\x12\x16\n" +
	"\x06Remark\x18\x04 \x01(\tR\x06Remark\x12\x14\n" +
	"\x05Force\x18\x05 \x01(\bR\x05Force\"|\n" +
	"\x11ChangeAssetsReply\x124\n" +
	"\fChangeAssets\x18\x01 \x01(\v2\x10.pb.ChangeAssetsR\fChangeAssets\x121\n" +
	"\vFinalAssets\x18\x02 \x01(\v2\x0f.pb.FinalAssetsR\vFinalAssets\"\"\n" +
	"\fChangeAssets\x12\x12\n" +
	"\x04Gold\x18\x01 \x01(\x03R\x04Gold\"!\n" +
	"\vFinalAssets\x12\x12\n" +
	"\x04Gold\x18\x01 \x01(\x03R\x04Gold\"#\n" +
	"\x0fFetchAssetsArgs\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x03R\x03UID\"&\n" +
	"\x10FetchAssetsReply\x12\x12\n" +
	"\x04Gold\x18\x01 \x01(\x03R\x04Gold2\xbc\x01\n" +
	"\x06Assets\x127\n" +
	"\n" +
	"InitAssets\x12\x12.pb.InitAssetsArgs\x1a\x13.pb.InitAssetsReply\"\x00\x12:\n" +
	"\vFetchAssets\x12\x13.pb.FetchAssetsArgs\x1a\x14.pb.FetchAssetsReply\"\x00\x12=\n" +
	"\fChangeAssets\x12\x14.pb.ChangeAssetsArgs\x1a\x15.pb.ChangeAssetsReply\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_assets_proto_rawDescOnce sync.Once
	file_assets_proto_rawDescData []byte
)

func file_assets_proto_rawDescGZIP() []byte {
	file_assets_proto_rawDescOnce.Do(func() {
		file_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)))
	})
	return file_assets_proto_rawDescData
}

var file_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_assets_proto_goTypes = []any{
	(*InitAssetsArgs)(nil),    // 0: pb.InitAssetsArgs
	(*InitAssetsReply)(nil),   // 1: pb.InitAssetsReply
	(*ChangeAssetsArgs)(nil),  // 2: pb.ChangeAssetsArgs
	(*ChangeAssetsReply)(nil), // 3: pb.ChangeAssetsReply
	(*ChangeAssets)(nil),      // 4: pb.ChangeAssets
	(*FinalAssets)(nil),       // 5: pb.FinalAssets
	(*FetchAssetsArgs)(nil),   // 6: pb.FetchAssetsArgs
	(*FetchAssetsReply)(nil),  // 7: pb.FetchAssetsReply
}
var file_assets_proto_depIdxs = []int32{
	4, // 0: pb.ChangeAssetsReply.ChangeAssets:type_name -> pb.ChangeAssets
	5, // 1: pb.ChangeAssetsReply.FinalAssets:type_name -> pb.FinalAssets
	0, // 2: pb.Assets.InitAssets:input_type -> pb.InitAssetsArgs
	6, // 3: pb.Assets.FetchAssets:input_type -> pb.FetchAssetsArgs
	2, // 4: pb.Assets.ChangeAssets:input_type -> pb.ChangeAssetsArgs
	1, // 5: pb.Assets.InitAssets:output_type -> pb.InitAssetsReply
	7, // 6: pb.Assets.FetchAssets:output_type -> pb.FetchAssetsReply
	3, // 7: pb.Assets.ChangeAssets:output_type -> pb.ChangeAssetsReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assets_proto_init() }
func file_assets_proto_init() {
	if File_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_proto_rawDesc), len(file_assets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assets_proto_goTypes,
		DependencyIndexes: file_assets_proto_depIdxs,
		MessageInfos:      file_assets_proto_msgTypes,
	}.Build()
	File_assets_proto = out.File
	file_assets_proto_goTypes = nil
	file_assets_proto_depIdxs = nil
}
